GET http://localhost:3000/players/
###

POST http://localhost:3000/players/
Content-Type:application/json
{
    "player_name":"Vishal",
    "jersey_number":17,
    "role":"Bowler"
}
###

GET http://localhost:3000/players/1/
###

PUT http://localhost:3000/players/1/

{
    "player_id":1,
    "player_name":"ravi",
    "jersey_number":18,
    "role":"All-rounder"
}
###

DELETE http://localhost:3000/players/1/